/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IntradayChart: typeof import('./components/IntradayChart.vue')['default']
    KlineChart: typeof import('./components/KlineChart.vue')['default']
    PriceChange: typeof import('./components/PriceChange.vue')['default']
    QuoteList: typeof import('./components/QuoteList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
